# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4842ebb3785fa9a5b0e7ea88da1c90bd444be7e436478fb25fd3b5954ec7818a4210b7347502a6c82595e0ffcaf59575b59f3903465441d24901c1e775881af1

test:
  secret_key_base: 5d243cd9c2ffad014d259167a31d50164a0e653916a367b33c80868f9b37207f9dc7c8561309028b554182a0c627b6305494b5cee8dc01e8833a9c8514ec8e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
